#ifndef __WINDEFS_H__
#define __WINDEFS_H__

#define MONITOR_WIDTH	1280
#define MONITOR_HEIGHT	800

#define SAFE_MARGIN	0

#define RGB(r, g, b)	((((r) & 0xFF) << 16) + (((g) & 0xFF) << 8) + ((b) & 0xFF))
#define GRAY(g)		(RGB((g), (g), (g)))

#define WINDOW_BORDER_COLOR	GRAY(180)
#define WINDOW_BACKGROUND_COLOR	GRAY(200)

#define WINDOW_SHADOW_OFFSET	10
#define WINDOW_SHADOW_COLOR	GRAY(20)

#define BORDER_THICKNESS	10

#define TOP_BAR_HEIGHT		50
#define TOP_BAR_BUTTON_SIZE	TOP_BAR_HEIGHT - 2 * TOP_BAR_BUTTON_MARGIN
#define TOP_BAR_BUTTON_MARGIN	5

#define TOP_BAR_TEXT_MARGIN	15
#define TOP_BAR_TEXT_SIZE	(TOP_BAR_HEIGHT - 2 * TOP_BAR_TEXT_MARGIN)

#define BACKGROUND_COLOR	RGB(0, 100, 255)
#define THEME_COLOR		RGB(0x00, 0xD5, 0xFF)
#define EXIT_BUTTON_COLOR	RGB(255, 0, 0)
#define MAX_BUTTON_COLOR	RGB(0, 0, 255)
#define MIN_BUTTON_COLOR	RGB(0, 255, 255)

#define TOP_BAR_BUTTON_Y_OFFSET		TOP_BAR_BUTTON_MARGIN
#define EXIT_BUTTON_X_OFFSET(width)	((width) - TOP_BAR_BUTTON_SIZE + TOP_BAR_BUTTON_MARGIN)
#define MAX_BUTTON_X_OFFSET(width)	((width) - 2 * TOP_BAR_BUTTON_SIZE + TOP_BAR_BUTTON_MARGIN)
#define MIN_BUTTON_X_OFFSET(width)	((width) - 3 * TOP_BAR_BUTTON_SIZE + TOP_BAR_BUTTON_MARGIN)

#define COMP_BUTTON_COLOR		GRAY(180)
#define COMP_BUTTON_OUTLINE_COLOR	GRAY(0)
#define COMP_BUTTON_MARGIN		2
#define COMP_BUTTON_TEXT_MARGIN		15

#define DESKTOP_ICON_WIDTH	50
#define DESKTOP_ICON_HEIGHT	75
#define DESKTOP_ICON_MARGIN	20

#define WELCOME_WINDOW_WIDTH	500
#define WELCOME_WINDOW_HEIGHT	300
#define WELCOME_WINDOW_X	((MONITOR_WIDTH - WELCOME_WINDOW_WIDTH) / 2)
#define WELCOME_WINDOW_Y	((MONITOR_HEIGHT - WELCOME_WINDOW_HEIGHT) / 2)
#define WELCOME_MSG_SIZE	20
#define WELCOME_BUTTON_WIDTH	200
#define WELCOME_BUTTON_HEIGHT	50

#define ICON_TEXT_SIZE	7

#endif
